name: NPM

on:
  push:
    branches:
      - 'master'
  release:
    types:
      - published

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --freeze-lockfile
      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --freeze-lockfile
      - name: Test
        run: yarn test

  publish_to_npm:
    name: Build and Publish to NPM
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    if: github.event_name == 'release'
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --freeze-lockfile
      - name: Build and publish
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          yarn build
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_to_ghcr:
    name: Publish to GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - lint
      - test
    if: github.event_name == 'release'
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'
            registry-url: https://npm.pkg.github.com/
        - name: Install dependencies
          run: yarn install --freeze-lockfile
        - name: Publish to GitHub Release
          run: |
            npm config set "//npm.pkg.github.com/:_authToken" "${NPM_TOKEN}"
            yarn build
            yarn publish --access public
          env:
            NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}